export const TASK_VIEW_KNOWLEDGE = `Task status is an on-demand, read-only projection of an existing owner, not a scheduler, job store, audit archive or background monitor. The first supported source is one durable workflow run selected by workflow:<runId>, where runId is its exact 64-character lowercase hexadecimal reference. Use an ID already supplied by the source; do not enumerate or guess IDs. The existing workflow owner publishes content-free metadata only after its own durable save. Source lookup reads a bounded process-local projection, never a workflow actor RPC, database fallback or provider; the worker's existing host authorization/delivery RPC fences still apply. The source owner's synchronous guard checks the original requester, conversation/thread, original source authority and deletion revision, and rejects an outdated publication or an inactive actor incarnation. The returned workflow-source fingerprint identifies that exact authenticated source without exposing raw identities; it is provenance, not an access token or actor lookup key. Knowing an ID, sharing an owner-private audience or reading this guidance never grants access to another conversation's work.

The task view distinguishes queued, running, waiting, blocked, unknown, complete, failed and cancelled. It reports bounded counts of the source journal's raw receipt statuses, not private source code, arguments, results, reports or errors. Journal entries can describe both a wrapper and its underlying call: counts are not a count of distinct external effects. Unknown or inconsistent receipts must not become complete. Complete describes the source run and its observed receipts only; neither aggregate status nor absent/pruned history proves all effects settled. Cancelled does not mean fenced, fully settled, undone or safe to reassign a resource. An irreversible effect may have completed or remain unknown after cancellation.

Delivery stays unknown unless there is a separately linked delivery receipt; this first workflow projection has no such link. A completed run or notify-shaped operation name does not prove a message was sent, read or useful. operationIds is empty because journal names are not linked provider operation IDs; empty does not mean no effects occurred. Source observations expire one minute after capture by the owner, not one minute after inspection. Reads never refresh evidence. The projection holds at most 128 last-published entries in this process, prunes expired entries on access/publication, and has no persistence, timers, backfill or actor wakeup. Missing, expired, evicted, post-restart or inactive-source evidence is unavailable/unknown, not failure or completion; do not wake a workflow or rerun it to fill the gap. The workflow definition revision is not a deployed Git revision. Null/unavailable also does not distinguish denied, revoked or deleted work; never infer foreign existence. These snapshots are neither live provider verification nor reusable authorization.

Current authorization rechecks may read existing synchronous deletion/source-authority stores, including SQLite. No-wake does not mean no I/O: preserve these revocation checks. They do not reconstruct workflow actor state or create a new store; the projection retains and returns only minimized metadata.

Each non-null read registers its exact final object with an invocation-local host guard. The host checks the original source publication/incarnation, current authorization/deletion and original expiry through the first synchronous insertion of the minimized observation into worker history. Missing registration or invalidation before that insertion yields unavailable, without rereading or waking the source. The worker discards these guards after publication or abandonment and before persistence; it never saves the raw source snapshot, reader or projection cache in history. This check authorizes first history publication, not later model/provider dispatch or continuing freshness. Once admitted, the minimized text is ordinary historical evidence with its original observedAt/expiresAt: a later source-only invalidation does not erase it or make it current again. Actual forgetting, deletion or revocation still cancels the worker and clears its history through the existing host controls. Do not confuse source inactivity with forgetting or infer permission to reuse expired evidence as current authority.

Only the exposed execution-worker action can inspect. The host retains the captured/current capability ceiling, source/deletion, cancellation and delivery fences before and after the read. Missing tasks integration, a manual disable or an unavailable worker is a blocker: explain it and request operator review of that prerequisite, not another account, credential or broader access. No provider call, enrollment, purchase, polling, new notification, retry, stop or queue edit is performed by inspection. Existing workflow/intent owners retain cancellation, reconciliation and recovery; use only separately exposed authorized controls. Never duplicate a run, replay an unknown effect, take over recovery, or treat hide/archive as cancellation.

This slice does not supply authorization-audit joins, task costs, interruption/correction measurements, usefulness feedback, attention savings, workboard leases or steering. Keep those unknown rather than inferring value from token counts, task completion or zero linked receipts. Autonomous purchases, orders, money transfers and new financial commitments are prohibited, including through Stripe Link. Configured inference and built-in tools are ordinary authorized tool use, not purchases; do not require per-account billing/no-charge attestation or impose artificial token/dollar admission caps. Preserve existing permissions, privacy, cancellation, bounded concurrency and real provider quotas/rate limits. Inspection adds no authority to transact.`;

export const TASK_VIEW_HELP =
  'Only when the current response schema exposes s05.task-inspection, use capability:{id:"s05.task-inspection",command:{action:"inspect",id:"workflow:<runId>"}} with the exact known workflow run reference, empty text and no other action. Read the complete JSON observation and preserve source scope, owner capture time, raw receipt counts and delivery uncertainty in your report. Do not substitute workflow actor presentation/inspect RPCs, mutable worker/research summaries, raw KV or eventless artifact-viewer access: actor RPCs can wake and resume work even when the action body is read-only. Inspect once for the current question; no polling, automatic retries or new attempt is implied.';
