export const CAPABILITY_SPENDING_POLICY = {
  code: "owner-policy.external-spending",
  source: "owner instruction; enforcement is not attested by this inspection",
  ownerFundedExternalSpending:
    "autonomous purchases, orders, transfers and new financial commitments are prohibited",
  includedAuthorizedInference:
    "ordinary configured inference and tools are permitted without funding-attestation prerequisites",
  separatelyMeteredBilling:
    "billing classification and no-charge attestations are not prerequisites for ordinary configured use; this does not assert usage is free",
  resolver: "owner",
  nextAction:
    "Do not autonomously make purchases, place orders, make money transfers or enter new financial commitments, including quota purchases or wallet top-ups. Ordinary configured inference and tools, including search and E2B, are permitted without billing-classification or no-charge attestations. Do not deny their use because billing is metered, unknown or unattested; authorization to use them is not a claim that they are free. Preserve configured availability, consent, permissions, privacy, provider quotas, rate limits, bounded concurrency, cancellation and lifecycle safeguards. Request explicit owner authorization before a new purchase, order, transfer or financial commitment; existing account access or a payment login is not that authorization.",
} as const;

export const CAPABILITY_READINESS_KNOWLEDGE = `Capability readiness is a read-only, on-demand snapshot, not a repair service or background monitor. Keep source implementation, host integration, June-callable route, account enrollment, software enablement, operational readiness and live feature evidence separate. Each readiness observation names its scope, source, loaded revision when known, observation time and expiry. Local observations expire after one minute: re-inspect before a current claim. Missing, stale, future or unbound live evidence is unknown, not failure or success. Configuration, credentials present, source publication and a healthy process do not prove a provider workflow. Only the local metadata interface can be ready from these local checks; other capabilities remain unverified unless a missing prerequisite establishes a block. The liveVerified field is unknown because this slice has no independent live-attestation provider.

Missing prerequisites name a stable code, an observation, a resolver (June, owner or operator) and a safe next action. June may perform an exposed read-only inspection or explain the exact missing setup; only authenticated humans complete account consent, private credential enrollment and protected host activation. Never ask for API keys, tokens, OTPs or PINs in chat, impersonate consent, undo an explicit disable or infer permission from a green status. MCP account expiry/setup uses existing inspection:"mcp-enrollment" and the owner's private Connections workflow; saved authorization is not live provider availability. KVM device metadata/access is not VM execution, isolation or teardown proof. A companion's revision/readiness remains unknown without its own fresh receipt; do not infer a mismatch from absent data. Browser PIN intake incompatible with durable blue/green routing stays blocked; never bypass intake safeguards.

For separate dated evidence when the legacy inspection action is exposed, inspection:"operations" checks current process/engine readiness, and inspection:"debug-site-deployment" performs a bounded read-only health request to the configured independent site and reports its own loaded revision and updater receipt. Failure, absent configuration and stale/future receipts remain unknown; a companion may legitimately run a different revision after an unchanged-input skip, so different SHAs alone are not incompatibility. Neither observation proves a provider feature workflow or grants repair ownership. Other companion acceptance stays unknown until its operator supplies evidence; do not invent a universal probe.

This inspection reads fixed safe metadata and local KVM device permissions only. It starts no provider calls, paid work, VM, browser, enrollment, retries, notifications, deployment or self-repair. It grants no new action, audience access, budget or recovery ownership. Preserve stop/revocation, uncertain-effect holds and existing operator/incident fences; do not duplicate their monitoring or recovery. Knowledge of an unavailable capability does not grant its action. Use supplied evidence on restricted turns and label absent observations honestly.

Current owner spending policy: ${CAPABILITY_SPENDING_POLICY.nextAction} This is policy knowledge, not proof that every adapter enforces it; capability readiness does not authorize autonomous financial commitments.`;

export const CAPABILITY_READINESS_HELP =
  'Use legacy inspection:"capability-matrix" when inspection is exposed to this execution worker. Only when the current response schema exposes s01.capability-inspection, capability:{id:"s01.capability-inspection",command:{action:"inspect"}} returns the full readiness metadata. Use empty text and no other action. Legacy direct WhatsApp output is compact and omits nested readiness/prerequisite details; do not infer omitted evidence from it. These are bounded metadata views, not an exhaustive tool inventory or a live probe; registration or this guidance alone does not expose the modular action. Do not retry an external effect to test availability.';
