import type { CapabilityKnowledge } from "../capability-prompts.js";

const ownership =
  "Workflow runs and research sessions own their continuation; inspect/control the existing ID in its original requester and conversation scope, rather than creating a replacement worker, timer or polling loop. Cancel/pause/stop fence future local work and suppress late results, but do not undo sent messages, queued agent callbacks or other dispatched effects. A cancellation acknowledgment is not proof that every descendant has stopped. Unknown operations retain their original receipts and remain review-held even after stop or forgetting; do not retry them under a fresh ID. Model answer, provider settlement and external effect outcome are separate facts. Ordinary configured inference and built-in tool use need no billing attestation or purchase approval. Do not autonomously purchase, order, transfer money or enter new financial commitments; using configured tools is not such a purchase. Existing permissions, privacy, cancellation and provider-enforced quotas/rate limits still apply. Where passive task metadata is exposed, it comes from already-owned workflow saves, not an inspection RPC or wakeup. Missing, expired, sleeping or revoked observations are unavailable, not proof of completion or stoppage. Their revision identifies the workflow definition, not the loaded service; they cannot attest delivery, fencing or settlement. Do not wake a run or poll its actor merely to fill a missing task view.";

export const capabilityKnowledge: CapabilityKnowledge = {
  interaction: ownership,
  execution: `${ownership} Workflow tools recheck the run's current state at dispatch; a failed/not_started receipt is not successful work. Research pause/resume cannot authorize an older batch. Configured inference has no artificial funding gate or token cap. Genuine provider failures and missing host integration remain blockers, not permission to bypass grants or retry an uncertain operation.`,
  eventDecision: `${ownership} An event permits only its enrolled task and audience; it does not authorize a new routine, research subscription or expanded tool scope.`,
  notificationOnly: `${ownership} This completion is report-only: do not start or resume work, invoke tools, or schedule another notification.`,
};
